-- Expand the matchable vocabulary around Guyana's petroleum support economy.
-- Sources checked 2026-09-05:
--   * Local Content Register opportunities:
--     https://lcregister.petroleum.gov.gy/opportunities/
--   * Ministry of Education TVET resources:
--     https://education.gov.gy/web2/index.php/technical-vocational-education?format=html
--   * Board of Industrial Training:
--     https://srms.bit.gov.gy/
--   * Ministry of Natural Resources annual-plan guideline:
--     https://petroleum.gov.gy/wp-content/uploads/2025/01/MNR-Local-Content-Annual-Plan-Submission-Guideline-Version-3.pdf
--
-- These are controlled capability and experience concepts, not automatic
-- credentials. Extracted evidence remains pending until the applicant reviews
-- it, and only confirmed records can affect a match.

insert into public.qualifications (slug, name, category, description)
values
  ('offshore-operations', 'Offshore Operations', 'experience', 'Experience working in an offshore operating environment; verify the role, employer, and safety requirements.'),
  ('onshore-operations', 'Onshore Operations', 'experience', 'Experience supporting onshore industrial or petroleum operations.'),
  ('hse-supervision', 'HSE Supervision', 'experience', 'Coordinates health, safety, and environmental activities; this is not a safety certification.'),
  ('pipefitting', 'Pipefitting', 'technical_skill', 'Installs, maintains, and repairs pipework and fittings.'),
  ('plumbing', 'Plumbing', 'technical_skill', 'Installs and maintains water, drainage, and building plumbing systems.'),
  ('pipe-welding', 'Pipe Welding', 'technical_skill', 'Welds pipe and pipeline joints; any welding certification must be verified separately.'),
  ('sandblasting-and-coating', 'Sandblasting and Coating', 'technical_skill', 'Prepares and coats metal or pipe surfaces using abrasive blasting and protective coatings.'),
  ('refrigeration-and-air-conditioning', 'Refrigeration and Air Conditioning', 'technical_skill', 'Installs, services, and troubleshoots refrigeration, air-conditioning, and HVAC equipment.'),
  ('carpentry', 'Carpentry', 'technical_skill', 'Builds, repairs, and finishes timber structures and site fixtures.'),
  ('masonry', 'Masonry', 'technical_skill', 'Builds and repairs block, brick, concrete, and related structures.'),
  ('steel-fixing', 'Steel Fixing', 'technical_skill', 'Cuts, bends, and places reinforcing steel for concrete construction.'),
  ('marine-deck-operations', 'Marine Deck Operations', 'technical_skill', 'Performs practical deck, line-handling, cargo, and vessel-support duties.'),
  ('diving-operations', 'Diving Operations', 'experience', 'Describes diving or underwater work reported by the applicant; it is not proof of a commercial-diving certificate.'),
  ('cargo-handling', 'Cargo Handling', 'technical_skill', 'Receives, secures, moves, and records cargo and materials.'),
  ('dredging-operations', 'Dredging Operations', 'technical_skill', 'Supports dredging, dredge equipment, and marine earthworks.'),
  ('surveying', 'Surveying', 'technical_skill', 'Collects and records land, marine, construction, or asset measurements.'),
  ('metrology', 'Metrology', 'technical_skill', 'Uses measurement, calibration, and inspection practices.'),
  ('environmental-fieldwork', 'Environmental Fieldwork', 'technical_skill', 'Collects field observations and samples for environmental monitoring.'),
  ('industrial-cleaning', 'Industrial Cleaning', 'technical_skill', 'Cleans industrial facilities, equipment, and work areas using safe procedures.'),
  ('waste-management', 'Waste Management', 'technical_skill', 'Handles, separates, stores, transports, or documents waste safely.'),
  ('ventilation-systems', 'Ventilation Systems', 'technical_skill', 'Installs, services, or inspects industrial ventilation systems.'),
  ('ict-network-support', 'ICT and Network Support', 'technical_skill', 'Installs, supports, or troubleshoots computers, networks, and communications equipment.'),
  ('office-administration', 'Office Administration', 'experience', 'Performs office coordination, records, scheduling, and administrative support.'),
  ('human-resources-administration', 'Human Resources Administration', 'experience', 'Supports recruitment, personnel records, onboarding, and employee administration.'),
  ('finance-and-accounting', 'Finance and Accounting', 'experience', 'Supports bookkeeping, accounting, budgeting, invoicing, or financial administration.'),
  ('communications-and-public-relations', 'Communications and Public Relations', 'experience', 'Supports internal communications, public information, media, or community engagement.'),
  ('procurement-and-logistics', 'Procurement and Logistics', 'experience', 'Coordinates purchasing, suppliers, transport, inventory, and materials flow.'),
  ('accommodation-services', 'Accommodation Services', 'experience', 'Supports lodging, guest services, housekeeping coordination, or accommodation operations.'),
  ('catering-and-food-safety', 'Catering and Food Safety', 'technical_skill', 'Prepares, serves, or supervises food using safe catering practices.'),
  ('custodial-services', 'Custodial Services', 'technical_skill', 'Performs janitorial, custodial, and facility-cleaning duties.'),
  ('security-operations', 'Security Operations', 'technical_skill', 'Performs site, access-control, patrol, or security-support duties.'),
  ('medical-support', 'Medical Support', 'technical_skill', 'Supports clinic, first-response, medical administration, or occupational-health activities.'),
  ('domestic-services', 'Domestic Services', 'experience', 'Provides household, domestic, or residential support services.'),
  ('transportation-and-personnel-driving', 'Transportation and Personnel Driving', 'technical_skill', 'Drives people, materials, or commercial vehicles safely for work.'),
  ('local-content-compliance', 'Local Content Compliance', 'compliance', 'Understands local-content registration, reporting, or compliance administration.'),
  ('gold-mining-and-alluvial-work', 'Gold Mining and Alluvial Work', 'experience', 'Experience in gold mining, alluvial work, or related site and equipment activities.'),
  ('marine-vessel-support', 'Marine Vessel Support', 'experience', 'Supports marine vessels, shore bases, ports, or offshore supply operations.'),
  ('drilling-support', 'Drilling Support', 'experience', 'Supports drilling-site, rig, materials, or field-service activities; verify the specific trade.'),
  ('surf-operations', 'SURF Operations', 'experience', 'Experience around subsea, umbilical, riser, or flowline support; verify the specific trade.')
on conflict (slug) do nothing;

insert into public.qualification_aliases (qualification_id, alias)
select qualification.id, alias_data.alias
from (
  values
    ('offshore-operations', 'Offshore Technician'),
    ('offshore-operations', 'Offshore Operations'),
    ('offshore-operations', 'Offshore Work'),
    ('offshore-operations', 'Offshore Maintenance'),
    ('onshore-operations', 'Onshore Technician'),
    ('onshore-operations', 'Onshore Operations'),
    ('onshore-operations', 'Onshore Work'),
    ('hse-supervision', 'Safety Officer'),
    ('hse-supervision', 'HSE Officer'),
    ('hse-supervision', 'Safety Supervisor'),
    ('hse-supervision', 'Health and Safety Officer'),
    ('mechanical-maintenance', 'Mechanic'),
    ('mechanical-maintenance', 'Mechanical Technician'),
    ('mechanical-maintenance', 'Maintenance Mechanic'),
    ('mechanical-maintenance', 'Industrial Mechanic'),
    ('welding-fabrication', 'Welder'),
    ('welding-fabrication', 'Welding'),
    ('pipefitting', 'Pipe Fitter'),
    ('pipefitting', 'Pipe Fitting'),
    ('pipefitting', 'Piping'),
    ('plumbing', 'Plumber'),
    ('plumbing', 'Plumbing Maintenance'),
    ('plumbing', 'Water Line Repair'),
    ('pipe-welding', 'Pipe Welder'),
    ('pipe-welding', 'Pipeline Welding'),
    ('pipe-welding', 'Pipe Welding'),
    ('sandblasting-and-coating', 'Sandblaster'),
    ('sandblasting-and-coating', 'Abrasive Blasting'),
    ('sandblasting-and-coating', 'Pipe Coating'),
    ('refrigeration-and-air-conditioning', 'Refrigeration Technician'),
    ('refrigeration-and-air-conditioning', 'Air Conditioning Technician'),
    ('refrigeration-and-air-conditioning', 'HVAC Technician'),
    ('carpentry', 'Carpenter'),
    ('masonry', 'Mason'),
    ('masonry', 'Block Work'),
    ('masonry', 'Bricklaying'),
    ('steel-fixing', 'Steel Fixer'),
    ('steel-fixing', 'Rebar Worker'),
    ('steel-fixing', 'Reinforcing Steel'),
    ('marine-deck-operations', 'Deckhand'),
    ('marine-deck-operations', 'Deck Crew'),
    ('marine-deck-operations', 'Marine Deckhand'),
    ('diving-operations', 'Diver'),
    ('diving-operations', 'Diving'),
    ('diving-operations', 'Underwater Work'),
    ('cargo-handling', 'Cargo Handler'),
    ('cargo-handling', 'Cargo Operations'),
    ('cargo-handling', 'Cargo Management'),
    ('dredging-operations', 'Dredge Operator'),
    ('dredging-operations', 'Dredging'),
    ('surveying', 'Surveyor'),
    ('surveying', 'Land Surveying'),
    ('surveying', 'Marine Surveying'),
    ('metrology', 'Measurement Technician'),
    ('metrology', 'Calibration Technician'),
    ('environmental-fieldwork', 'Environmental Technician'),
    ('environmental-fieldwork', 'Environmental Monitoring'),
    ('industrial-cleaning', 'Industrial Cleaner'),
    ('industrial-cleaning', 'Industrial Cleaning'),
    ('waste-management', 'Waste Handler'),
    ('waste-management', 'Waste Management'),
    ('ventilation-systems', 'Ventilation Technician'),
    ('ventilation-systems', 'Industrial Ventilation'),
    ('ict-network-support', 'IT Support'),
    ('ict-network-support', 'Network Technician'),
    ('ict-network-support', 'ICT Support'),
    ('office-administration', 'Office Administrator'),
    ('office-administration', 'Administrative Assistant'),
    ('office-administration', 'Admin Clerk'),
    ('human-resources-administration', 'Human Resources'),
    ('human-resources-administration', 'HR Assistant'),
    ('human-resources-administration', 'Personnel Administration'),
    ('finance-and-accounting', 'Accountant'),
    ('finance-and-accounting', 'Bookkeeping'),
    ('finance-and-accounting', 'Finance Assistant'),
    ('communications-and-public-relations', 'Communications'),
    ('communications-and-public-relations', 'Public Relations'),
    ('communications-and-public-relations', 'Media Relations'),
    ('procurement-and-logistics', 'Procurement'),
    ('procurement-and-logistics', 'Logistics Coordinator'),
    ('procurement-and-logistics', 'Supply Chain'),
    ('accommodation-services', 'Accommodation Services'),
    ('accommodation-services', 'Lodging Services'),
    ('accommodation-services', 'Hotel Housekeeping'),
    ('catering-and-food-safety', 'Cook'),
    ('catering-and-food-safety', 'Caterer'),
    ('catering-and-food-safety', 'Food Service'),
    ('catering-and-food-safety', 'Food Safety'),
    ('custodial-services', 'Custodian'),
    ('custodial-services', 'Janitor'),
    ('custodial-services', 'Janitorial'),
    ('custodial-services', 'Cleaning Attendant'),
    ('security-operations', 'Security Guard'),
    ('security-operations', 'Security Officer'),
    ('security-operations', 'Access Control'),
    ('medical-support', 'Medical Assistant'),
    ('medical-support', 'Clinic Support'),
    ('medical-support', 'Occupational Health Support'),
    ('domestic-services', 'Domestic Worker'),
    ('domestic-services', 'Domestic Services'),
    ('domestic-services', 'Household Services'),
    ('transportation-and-personnel-driving', 'Driver'),
    ('transportation-and-personnel-driving', 'Bus Driver'),
    ('transportation-and-personnel-driving', 'Personnel Transport'),
    ('transportation-and-personnel-driving', 'Truck Driver'),
    ('local-content-compliance', 'Local Content'),
    ('local-content-compliance', 'Local Content Registration'),
    ('local-content-compliance', 'Compliance Administration'),
    ('gold-mining-and-alluvial-work', 'Gold Miner'),
    ('gold-mining-and-alluvial-work', 'Gold minor'),
    ('gold-mining-and-alluvial-work', 'Gold Mining'),
    ('gold-mining-and-alluvial-work', 'Alluvial Mining'),
    ('gold-mining-and-alluvial-work', 'Dredge Mining'),
    ('marine-vessel-support', 'Vessel Support'),
    ('marine-vessel-support', 'Marine Vessel Support'),
    ('marine-vessel-support', 'Port Support'),
    ('drilling-support', 'Drilling Support'),
    ('drilling-support', 'Rig Support'),
    ('drilling-support', 'Drilling Operations Support'),
    ('surf-operations', 'SURF'),
    ('surf-operations', 'Subsea Support'),
    ('surf-operations', 'Riser and Flowline Support')
) as alias_data(slug, alias)
join public.qualifications qualification on qualification.slug = alias_data.slug
on conflict (normalized_alias) do nothing;
