-- Company owners can create one-time recruiter invitations without handling
-- passwords. The invitation token is generated by the application; only its
-- SHA-256 hash is stored here.

alter table public.company_members
  add column invited_email text;

create unique index company_members_one_company_per_user_idx
  on public.company_members (user_id);

update public.company_members member
set invited_email = lower(auth_user.email)
from auth.users auth_user
where auth_user.id = member.user_id
  and auth_user.email is not null;

alter table public.company_members
  add constraint company_members_invited_email_normalized
  check (invited_email is null or invited_email = lower(btrim(invited_email)));

create table public.company_recruiter_invitations (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id) on delete cascade,
  email text not null,
  token_hash text not null unique,
  invited_by uuid not null references auth.users (id) on delete cascade,
  expires_at timestamptz not null,
  accepted_at timestamptz,
  accepted_by uuid references auth.users (id) on delete set null,
  revoked_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (company_id, email),
  constraint company_recruiter_invitation_email_normalized
    check (email = lower(btrim(email))),
  constraint company_recruiter_invitation_token_hash_format
    check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint company_recruiter_invitation_expiry_order
    check (expires_at > created_at),
  constraint company_recruiter_invitation_acceptance_complete
    check ((accepted_at is null) = (accepted_by is null))
);

create index company_recruiter_invitations_company_idx
  on public.company_recruiter_invitations (company_id, created_at desc);

create index company_recruiter_invitations_email_idx
  on public.company_recruiter_invitations (email)
  where accepted_at is null and revoked_at is null;

create trigger company_recruiter_invitations_set_updated_at
before update on public.company_recruiter_invitations
for each row execute function public.set_updated_at();

create or replace function private.is_company_owner(target_company_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.company_members member
    join public.companies company on company.id = member.company_id
    where member.company_id = target_company_id
      and member.user_id = (select auth.uid())
      and member.role = 'owner'::public.company_member_role
      and company.status = 'approved'::public.company_status
  );
$$;

revoke all on function private.is_company_owner(uuid) from public, anon;
grant execute on function private.is_company_owner(uuid) to authenticated;

alter table public.company_recruiter_invitations enable row level security;

revoke all on table public.company_recruiter_invitations from public, anon, authenticated;
grant select, insert, update on table public.company_recruiter_invitations to authenticated;
grant all on table public.company_recruiter_invitations to service_role;

create policy "Owners manage recruiter invitations"
on public.company_recruiter_invitations for all to authenticated
using ((select private.is_company_owner(company_id)))
with check (
  (select private.is_company_owner(company_id))
  and invited_by = (select auth.uid())
);

create policy "Recruiters read their active invitation"
on public.company_recruiter_invitations for select to authenticated
using (
  email = lower((select auth.jwt() ->> 'email'))
  and accepted_at is null
  and revoked_at is null
  and expires_at > timezone('utc', now())
);

create policy "Invited recruiters read their company"
on public.companies for select to authenticated
using (exists (
  select 1
  from public.company_recruiter_invitations invitation
  where invitation.company_id = companies.id
    and invitation.email = lower((select auth.jwt() ->> 'email'))
    and invitation.accepted_at is null
    and invitation.revoked_at is null
    and invitation.expires_at > timezone('utc', now())
));

create policy "Owners remove recruiters"
on public.company_members for delete to authenticated
using (
  role = 'recruiter'::public.company_member_role
  and (select private.is_company_owner(company_id))
);

create or replace function public.accept_company_recruiter_invitation(
  target_token_hash text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_id uuid := auth.uid();
  caller_email text := lower(auth.jwt() ->> 'email');
  invitation_record public.company_recruiter_invitations%rowtype;
begin
  if caller_id is null or caller_email is null then
    raise exception 'Authentication is required';
  end if;

  select * into invitation_record
  from public.company_recruiter_invitations invitation
  where invitation.token_hash = target_token_hash
    and invitation.email = caller_email
    and invitation.accepted_at is null
    and invitation.revoked_at is null
    and invitation.expires_at > timezone('utc', now())
  for update;

  if invitation_record.id is null then
    raise exception 'This recruiter invitation is invalid or has expired';
  end if;

  if exists (
    select 1
    from public.company_members member
    where member.user_id = caller_id
      and member.company_id <> invitation_record.company_id
  ) then
    raise exception 'This account already belongs to another company';
  end if;

  insert into public.company_members (company_id, user_id, role, invited_email)
  values (
    invitation_record.company_id,
    caller_id,
    'recruiter'::public.company_member_role,
    caller_email
  )
  on conflict (company_id, user_id) do update
  set invited_email = excluded.invited_email;

  update public.company_recruiter_invitations
  set accepted_at = timezone('utc', now()),
      accepted_by = caller_id
  where id = invitation_record.id;

  return invitation_record.company_id;
end;
$$;

revoke all on function public.accept_company_recruiter_invitation(text) from public, anon;
grant execute on function public.accept_company_recruiter_invitation(text) to authenticated;

-- New company owners should also have a roster email immediately.
create or replace function private.create_company_owner_membership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.requested_by is not null then
    insert into public.company_members (company_id, user_id, role, invited_email)
    select new.id, new.requested_by, 'owner', lower(auth_user.email)
    from auth.users auth_user
    where auth_user.id = new.requested_by
    on conflict (company_id, user_id) do nothing;
  end if;
  return new;
end;
$$;
